### ISSUE TITLE
fontawesome 5.2.0

### ISSUE THREAD

**Issue by garthtarr** [mitchelloharawild/icons#21]
I've tried to update to fontawesome 5.2.0... it works but it's not elegant.  I think I've included more fontawesome code than necessary so I didn't suggest it as a direct pull request.  

It can be found here: https://github.com/garthtarr/icon

Doesn't take very long to do, but there are a few extra icons available in 5.2.0 that aren't currently accessible with the icon package, would be great to see it officially supported.

**Comment by mitchelloharawild** [comment]
Looks okay. I'm holding off on updates for now because I would like to convert the package to use SVG icons instead of fonts later this month (#19). This will result in it being possible to update icon libraries without updating the package itself.

Glad you found your way around updating the libraries yourself.

**Comment by garthtarr** [comment]
Thanks, I look forward to the SVG update!
