### ISSUE TITLE
support for icons as html

### ISSUE THREAD

**Issue by nteetor** [mitchelloharawild/icons#23]
Hello hello, I am wondering if there are plans to support HTML return values. Currently, if I understand correctly, the icon utilities create character strings whose class or classes coupled with the strings' values determine what icon glyphs are printed. Unfortunately, shiny interprets these values simply as strings.

I see the package's description specifically mentions usage in R markdown documents. Is there are any chance the API could be extended to support usage in shiny applications? I am willing to put together a PR if shiny support is within the bounds of the package.

**Comment by mitchelloharawild** [comment]
Work has already started on rewriting this package from scratch ([here](https://github.com/mitchelloharawild/icon)) which implements things using SVG icons instead of font icons (many benefits here). As part of that, the package also returns HTML values as the print method.

The icon package should already work with shiny applications... Not sure why this is not the case (perhaps running shiny apps counts as an interactive environment?).

**Comment by nteetor** [comment]
Thank you for the quick reply. I missed these critical [lines](https://github.com/ropenscilabs/icon/blob/master/R/print.R#L31-L33). Insult to injury, I also launched my test shiny app in an interactive session. I look forward to following future updates in the new repo. Feel free to close.
