### ISSUE TITLE
Icons not showing using https://htmlpreview.github.io/

### ISSUE THREAD

**Issue by zhiiiyang** [mitchelloharawild/icons#24]
Hi, I am trying to use it in RMarkdown and preview the html file through https://htmlpreview.github.io/. The icons work just fine on my local computer but didn't show in the browser. Could you help me with solving this issue? Thank you!

<img width="193" alt="screen shot 2019-01-01 at 23 07 54" src="https://user-images.githubusercontent.com/7269113/50582824-36a17400-0e1a-11e9-9b34-5d4a1ebd66cf.png">

**Comment by mitchelloharawild** [comment]
Is the HTML file available online somewhere for me to investigate?

**Comment by zhiiiyang** [comment]
Thank you for the prompt reply. 

You can find this HTML file with a similar problem here. 
https://github.com/laeRusers/laocrug/blob/master/welcome/index.html

This is the HTML preview using the https://htmlpreview.github.io/
https://htmlpreview.github.io/?https://github.com/laeRusers/laocrug/blob/master/welcome/index.html

Missing icons are on slide 8 (the last one).

**Comment by mitchelloharawild** [comment]
This is an issue with htmlpreview. You can see in the console logs that mixed content is blocked, which is preventing these fonts from being loaded.
```
Blocked loading mixed active content “http://www.datatables.org/data/data.headers.xml../webfonts/fa-brands-400.ttf”
```
The package should work if used with GitHub pages, netlify, and most other services.

I've started on a complete re-write of this package to use SVG icons instead of webfont icons (https://github.com/mitchelloharawild/icon). I think these changes would work with htmlpreview, however this version probably won't be ready before your talk.

**Comment by zhiiiyang** [comment]
Thank you for the quick reply. I used https://raw.githack.com/ and all the icons work great. Also, http://htmlpreview.github.io is running into some issues and all the previewing functions aren't working today. So I might switch to another service. Thank you again!

**Comment by mitchelloharawild** [comment]
Great - glad you could get it working :)
