### ISSUE TITLE
Using icons in Rmarkdown titles

### ISSUE THREAD

**Issue by suzanbaert** [mitchelloharawild/icons#7]
Hi!

I was playing around in Icon to spice up some less serious reports. Inside text blocks it looks magnificent, but when I tried to use an icon inside an Rmarkdown title, the end result looked a bit funny. 
It added some text in front of the title: -title" class="section level1">

The issue did not go away when I added some text before the inline code

Any suggestions on how to fix this?
Thanks!
<br>

### *the code:*
<img width="400" alt="icontitleissuecode" src="https://user-images.githubusercontent.com/33345088/34423750-8f4c9888-ec1e-11e7-834c-ef533e9edcb2.PNG">

  <br>
  
### *what i got:*
<img width="307" alt="icontitleissue" src="https://user-images.githubusercontent.com/33345088/34423788-c39ca25e-ec1e-11e7-99da-ffb632a26e0a.PNG">

**Comment by mitchelloharawild** [comment]
Hi,

We were having a look into this during rOpenSci OzUnconference 2017, the issue seems to come from the output format. This issue doesn't seem to occur with xaringan::moon_reader, however most other formats (such as html_document and revealjs::revealjs_presentation) have this issue.

@yihui: Any thoughts for how this can be resolved within icon::fa()? Some way to protect the `<i>` tags perhaps?

**Comment by yihui** [comment]
Sounds like a bug of `rmarkdown::html_document` (`xaringan::moon_reder` is one of the few HTML output formats that is not based on `rmarkdown::html_document`), but I probably don't have time to investigate it in the near future. It does not sound like a good idea to me to use raw HTML in section titles in Markdown (it is not portable, but you probably don't care).

Anyway, if anyone can figure out the fix, I'd appreciate a pull request!

**Comment by mitchelloharawild** [comment]
Resolved by #31
